export const seoKeywordClusters = {
  core: [
    'brandwacht',
    'brandwacht inhuren',
    'brandwacht samenwerken',
    'brandwacht uitleg',
    'brandwacht verantwoordelijkheden',
    'brandwacht-inzet uitleg',
    'brandwachtenmarkt',
    'brandwacht tarieven zzp',
    'brandwacht tarieven 24/7',
    'dba-bewust samenwerken',
  ],
  platform: [
    'brandwacht initiatief',
    'kennisinitiatief brandwacht',
    'probrandwacht initiatief',
    'brandwacht platform',
    'kennisplatform brandwacht',
    'brandwacht kennisbank',
    'platform voor brandwacht',
    'uitleg samenwerking brandwacht',
    'rolafbakening brandwacht',
    'brandwacht afspraken uitleg',
    'brandwacht samenwerking uitleg',
    'uitleg brandwacht samenwerking',
    'uitlegbare veiligheid',
    'rol en verantwoordelijkheid brandwacht',
    'brandwacht rijksgediplomeerd uitleg',
  ],
  zzpFreelance: [
    'zelfstandige brandwacht',
    'zzp brandwacht samenwerken',
    'zzp brandwacht uitleg',
    'zzp brandwacht verantwoordelijkheden',
    'zzp brandwacht ondernemerschap',
    'brandwacht zelfstandig werken',
    'zelfstandig brandwacht uitleg',
    'zzp brandwacht positie',
    '1-op-1 samenwerking zzp brandwacht',
    'veiligheidswacht zelfstandig',
    'zelfstandige brandwacht uitleg',
    'mangatwacht zzp',
    'buitenwacht zzp',
  ],
  tariefInzicht: [
    'afspraken brandwacht',
    'uitlegbare samenwerking',
    'rolafbakening samenwerking',
    'verantwoordelijkheden opdrachtgevers',
    'verantwoordelijkheden zelfstandigen',
    'rolverdeling brandwacht',
    'verantwoordelijkheid brandwacht',
  ],
  niches: [
    'industriële brandwacht',
    'industriele brandwacht zzp',
    'brandwacht petrochemie',
    'brandwacht evenementen',
    'evenementen brandwacht zzp',
    'brandwacht bij storing',
    'brandwacht brandmeldinstallatie',
    'brandwacht heetwerkwacht',
    'brandwacht werkvergunning',
    'brandwacht kantoor',
    'brandwacht zorginstelling',
    'gasmeting',
    'gasmeter',
    'gasmeting brandwacht',
    'poort-qr check-in',
  ],
  processSpeed: [],
  positioning: [
    'rolverdeling brandwacht',
    'verantwoordelijkheid brandwacht',
    'dba-bewust samenwerken',
    'professioneel oordeel veiligheid',
    'veiligheid in de praktijk',
    'marktontwikkeling brandveiligheid',
    'uitlegbare samenwerking',
    'brandwacht rijksgediplomeerd',
  ],
  regulatory: [
    'veiligheidsregio',
    'veiligheidsregio brandwacht',
    'vr brandwacht',
    'bbl brandveiligheid',
    'besluit bouwwerken leefomgeving',
    'toezichthouder brandveiligheid',
    'brandveiligheid toezicht',
  ],
}
