export const seoKeywordClusters = {
  core: [
    'brandwacht',
    'brandwacht tarieven',
    'brandwacht uurtarief',
    'kosten brandwacht inhuren',
  ],
  platform: [
    'brandwacht platform',
    'platform voor brandwachten',
    'brandwacht planning platform',
    'brandwacht platform voor opdrachtgevers',
    'brandwacht matching platform',
    'brandwacht aanvragen platform',
    'brandwacht zonder bureau',
    'platform directe samenwerking',
    'brandwacht freelance platform',
    'brandwacht community platform',
    'platform brandwachten',
  ],
  zzpFreelance: [
    'zzp brandwacht opdrachten',
    'freelance brandwacht',
    'zzp brandwacht inhuren',
    'zzp brandwacht platform',
    'zzp brandwacht samenwerken',
    'zzp brandwacht community',
    'zzp brandwacht zonder intermediair',
    'directe samenwerking zzp brandwacht',
    'direct werk voor brandwachten',
    'veiligheidswacht zzp platform',
    'veiligheidswacht opdrachten zzp',
  ],
  tariefInzicht: [
    'eerlijk brandwacht tarief',
    'eerlijke brandwacht tarieven',
    'transparant tarief brandwacht',
    'brandwacht tarief zonder bureau',
    'netto tarief brandwacht',
    'brandwacht wat verdien ik echt',
    'brandwacht platform tarieven',
    'brandwacht tarief berekenen',
    'brandwacht calculator tarief',
    'brandwacht zzp tarieven',
    'brandwacht netto verdienen',
    'brandwacht zonder marge',
    'brandwacht tarief inzicht',
    'DBA-proof brandwacht',
    'brandwacht modelovereenkomst',
    'heldere tarieven',
    'toetsbare tariefafspraken',
    'toetsbaar tarief',
    'tariefopbouw brandwacht',
  ],
  niches: [
    'industriële brandwacht',
    'industriele brandwacht zzp',
    'brandwacht petrochemie',
    'brandwacht evenementen',
    'evenementen brandwacht zzp',
    'brandwacht bij storing',
    'brandwacht brandmeldinstallatie',
    'brandwacht heetwerkwacht',
    'brandwacht werkvergunning',
    'veiligheidswacht inhuren',
    'brandwacht kantoor',
    'brandwacht zorginstelling',
  ],
  processSpeed: [
    'brandwacht spoed',
    'brandwacht direct',
    'brandwacht direct inzetten',
    'brandwacht direct koppelen',
    'brandwacht aanvragen',
    'brandwacht zelf plannen',
    'brandwacht direct reageren',
    'spoed brandwacht inzet',
    'brandwacht opdracht ontvangen',
    'brandwacht beschikbaarheid app',
    '24/7 brandwacht direct',
    '24/7 brandwacht',
  ],
  positioning: [
    'rolverdeling brandwacht',
    'verantwoordelijkheid brandwacht',
    'DBA-bewust samenwerken',
    'professioneel oordeel veiligheid',
    'veiligheid in de praktijk',
  ],
};
