// lib/city-data.ts

export type CityRecordShape = {
  slug: string
  name: string
  latitude: number
  longitude: number
  venues?: string[]
  industrialAreas?: string[]
  sectorNotes?: string
  aliases?: string[]
  updatedAt?: string
}

export const CITY_DATA = [
  {
    slug: "amsterdam",
    name: "Amsterdam",
    latitude: 52.3676,
    longitude: 4.9041,
    venues: ["RAI", "Ziggo Dome", "ArenA-gebied"],
    industrialAreas: ["Westpoort", "Sloterdijk"],
    sectorNotes:
      "Hoge evenementendruk + veel bouw/verbouw (crowd & tijdelijke brandrisico’s).",
    aliases: ["ams", "amsterdam-centrum"],
    updatedAt: "2025-10-01",
  },
  {
    slug: "rotterdam",
    name: "Rotterdam",
    latitude: 51.9244,
    longitude: 4.4777,
    venues: ["Ahoy", "RTM Stage"],
    industrialAreas: ["Havengebied", "Botlek", "Europoort"],
    sectorNotes:
      "Sterke vraag industriële brandwachten (heetwerk/besloten ruimten), plus events.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "den-haag",
    name: "Den Haag",
    latitude: 52.0705,
    longitude: 4.3007,
    venues: ["World Forum", "Zuiderpark"],
    industrialAreas: ["Binckhorst"],
    sectorNotes:
      "Publieksveiligheid in stad/parken; projecten op en rond overheidshuisvesting.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "utrecht",
    name: "Utrecht",
    latitude: 52.0907,
    longitude: 5.1214,
    venues: ["Jaarbeurs", "TivoliVredenburg"],
    industrialAreas: ["Lage Weide"],
    sectorNotes:
      "Beurs/evenementen + logistiek; vaak toezicht bij tijdelijke installaties.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "eindhoven",
    name: "Eindhoven",
    latitude: 51.4416,
    longitude: 5.4697,
    venues: ["Evoluon", "Strijp-S"],
    industrialAreas: ["High Tech Campus", "Flight Forum"],
    sectorNotes:
      "Techcampus en verbouwprojecten; vraag naar BHV/VCA en werktuigbouw-omgeving.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "groningen",
    name: "Groningen",
    latitude: 53.2194,
    longitude: 6.5665,
    venues: ["Martiniplaza"],
    industrialAreas: ["Eemshaven (regio)"],
    sectorNotes:
      "Projectmatig industriewerk; piekjes rondom events en onderwijs.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "haarlem",
    name: "Haarlem",
    latitude: 52.3874, longitude: 4.6462,
    venues: ["PHIL Haarlem"],
    industrialAreas: ["Waarderpolder"],
    sectorNotes: "Veel renovatie/onderhoud + evenementen in en rond de binnenstad.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "amersfoort",
    name: "Amersfoort",
    latitude: 52.1561, longitude: 5.3878,
    venues: ["Flint"],
    industrialAreas: ["Isselt"],
    sectorNotes: "Mix van events en bouwtoezicht; logistieke knoop in de regio.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "zwolle",
    name: "Zwolle",
    latitude: 52.5168, longitude: 6.0830,
    venues: ["IJsselhallen"],
    industrialAreas: ["Marslanden"],
    sectorNotes: "Seizoenspieken door beurzen en regionale festivals.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "arnhem",
    name: "Arnhem",
    latitude: 51.9851, longitude: 5.8987,
    venues: ["Musis & Stadstheater"],
    industrialAreas: ["Kleefse Waard"],
    sectorNotes: "Projectmatig werk, tevens vraag naar crowd safety bij city-events.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "nijmegen",
    name: "Nijmegen",
    latitude: 51.8126, longitude: 5.8372,
    venues: ["Goffertpark"],
    industrialAreas: ["Nijmegen-Noord"],
    sectorNotes: "Pieken rond Vierdaagse; brandpreventie bij tijdelijke installaties.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "tilburg",
    name: "Tilburg",
    latitude: 51.5555, longitude: 5.0913,
    venues: ["013 Poppodium"],
    industrialAreas: ["Vossenberg"],
    sectorNotes: "Industrieel & logistiek toezicht, plus evenementen in het centrum.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "breda",
    name: "Breda",
    latitude: 51.5719, longitude: 4.7683,
    venues: ["Breepark"],
    industrialAreas: ["Hazeldonk"],
    sectorNotes: "Grote publieksevents en toezicht bij retail/nieuwbouw.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "s-hertogenbosch",
    name: "'s-Hertogenbosch",
    latitude: 51.6978, longitude: 5.3037,
    venues: ["Brabanthallen"],
    industrialAreas: ["De Rietvelden"],
    sectorNotes: "Beurzen & tijdelijke installaties; vraag naar BHV/VCA-profielen.",
    aliases: ["den-bosch","shertogenbosch"],
    updatedAt: "2025-10-01",
  },
  {
    slug: "maastricht",
    name: "Maastricht",
    latitude: 50.8514, longitude: 5.6910,
    venues: ["MECC Maastricht"],
    industrialAreas: ["Beatrixhaven"],
    sectorNotes: "Grensregio; events en industrie (chemie/food) wisselen elkaar af.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "heerlen",
    name: "Heerlen",
    latitude: 50.8882, longitude: 5.9795,
    venues: ["Parkstad Limburg Theater"],
    industrialAreas: ["Beitel"],
    sectorNotes: "Regio-projecten en onderhoudswerk, ook in zorg/onderwijs.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "enschede",
    name: "Enschede",
    latitude: 52.2215, longitude: 6.8937,
    venues: ["Grolsch Veste (omgeving)"],
    industrialAreas: ["Havengebied Enschede"],
    sectorNotes: "Technische projecten & education events; EHBO/BHV gevraagd.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "apeldoorn",
    name: "Apeldoorn",
    latitude: 52.2112, longitude: 5.9699,
    venues: ["Omnisport"],
    industrialAreas: ["Malkenschoten"],
    sectorNotes: "Sportevenementen & verbouwingen bij publieke voorzieningen.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "leeuwarden",
    name: "Leeuwarden",
    latitude: 53.2012, longitude: 5.7999,
    venues: ["WTC Expo (regio)"],
    industrialAreas: ["De Hemrik"],
    sectorNotes: "Regionale beurzen; opleveringen in woning-/utiliteitsbouw.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "alkmaar",
    name: "Alkmaar",
    latitude: 52.6324, longitude: 4.7534,
    venues: ["AFAS Stadion (omgeving)"],
    industrialAreas: ["Beverkoog"],
    sectorNotes: "Retailverbouwingen en crowd-safety bij stadsactiviteiten.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "dordrecht",
    name: "Dordrecht",
    latitude: 51.8133, longitude: 4.6901,
    venues: ["Energiehuis"],
    industrialAreas: ["Dordtse Kil"],
    sectorNotes: "Haven/industrie-omgeving: toezicht bij heetwerk en stops.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "leiden",
    name: "Leiden",
    latitude: 52.1601, longitude: 4.4970,
    venues: ["Stadsgehoorzaal"],
    industrialAreas: ["Bio Science Park (regio)"],
    sectorNotes: "Onderwijs/health-projecten; strenge compliance/vergunningen.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "haarlemmermeer",
    name: "Haarlemmermeer",
    latitude: 52.3010, longitude: 4.6653,
    venues: ["Expo Greater Amsterdam"],
    industrialAreas: ["Schiphol-omgeving"],
    sectorNotes: "Luchtvaart/logistiek; veel tijdelijke installaties & keuringen.",
    aliases: ["schiphol-regio"],
    updatedAt: "2025-10-01",
  },
  {
    slug: "zoetermeer",
    name: "Zoetermeer",
    latitude: 52.0607, longitude: 4.4940,
    venues: ["SilverDome (omgeving)"],
    industrialAreas: ["Bleizo"],
    sectorNotes: "Retail & leisure projecten; toezicht bij tijdelijke voorzieningen.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "zaanstad",
    name: "Zaanstad",
    latitude: 52.4570, longitude: 4.7510,
    venues: ["Hemkade (regio)"],
    industrialAreas: ["Achtersluispolder"],
    sectorNotes: "Food/industrie en evenementenmix in metropoolregio.",
    updatedAt: "2025-10-01",
  },
  {
    slug: "almere",
    name: "Almere",
    latitude: 52.3508, longitude: 5.2647,
    venues: ["Almere Centrum Events"],
    industrialAreas: ["De Vaart"],
    sectorNotes: "Snelle woningbouw; toezicht bij oplevering en brandmeldinstallaties.",
    updatedAt: "2025-10-01",
  },
 ] as const satisfies ReadonlyArray<CityRecordShape>

export type CityRecord = (typeof CITY_DATA)[number]
export type CitySlug = CityRecord['slug']
export const CITY_SLUGS = CITY_DATA.map(city => city.slug) as CitySlug[]
