// AUTO-GENERATED BY scripts/content/generate-city-copy.mjs
// City-specific frontstage copy for werkkaarten.
// Pas gerust handmatig aan als je wilt fine-tunen.

export type CityCopy = {
  slug: string;
  name: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  body: string;
  localCaseTitle: string;
  localCaseBody: string;
};

export const cityCopy: Record<string, CityCopy> = {
  "amsterdam": {
    "slug": "amsterdam",
    "name": "Amsterdam",
    "metaTitle": "Brandwacht-inzet in Amsterdam: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Amsterdam. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Amsterdam: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Amsterdam. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Amsterdam\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Amsterdam",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "rotterdam": {
    "slug": "rotterdam",
    "name": "Rotterdam",
    "metaTitle": "Brandwacht-inzet in Rotterdam: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Rotterdam. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Rotterdam: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Rotterdam. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Rotterdam\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Rotterdam",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "den-haag": {
    "slug": "den-haag",
    "name": "Den Haag",
    "metaTitle": "Brandwacht-inzet in Den Haag: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Den Haag. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Den Haag: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Den Haag. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Den Haag\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Den Haag",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "utrecht": {
    "slug": "utrecht",
    "name": "Utrecht",
    "metaTitle": "Brandwacht-inzet in Utrecht: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Utrecht. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Utrecht: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Utrecht. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Utrecht\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Utrecht",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "eindhoven": {
    "slug": "eindhoven",
    "name": "Eindhoven",
    "metaTitle": "Brandwacht-inzet in Eindhoven: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Eindhoven. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Eindhoven: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Eindhoven. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Eindhoven\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Eindhoven",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "tilburg": {
    "slug": "tilburg",
    "name": "Tilburg",
    "metaTitle": "Brandwacht-inzet in Tilburg: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Tilburg. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Tilburg: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Tilburg. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Tilburg\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Tilburg",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "groningen": {
    "slug": "groningen",
    "name": "Groningen",
    "metaTitle": "Brandwacht-inzet in Groningen: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Groningen. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Groningen: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Groningen. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Groningen\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Groningen",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "almere": {
    "slug": "almere",
    "name": "Almere",
    "metaTitle": "Brandwacht-inzet in Almere: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Almere. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Almere: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Almere. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Almere\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Almere",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "breda": {
    "slug": "breda",
    "name": "Breda",
    "metaTitle": "Brandwacht-inzet in Breda: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Breda. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Breda: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Breda. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Breda\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Breda",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  },
  "nijmegen": {
    "slug": "nijmegen",
    "name": "Nijmegen",
    "metaTitle": "Brandwacht-inzet in Nijmegen: verantwoordelijkheden en context | ProBrandwacht",
    "metaDescription": "Onafhankelijke uitleg over brandwacht-inzet in Nijmegen. Wat is verplicht, wie is verantwoordelijk en waar let je op in de praktijk?",
    "h1": "Brandwacht-inzet in Nijmegen: context en verantwoordelijkheden",
    "intro": "Publieke werkkaart voor Nijmegen. ProBrandwacht duidt hoe brandwacht-inzet uitlegbaar blijft — geen bureau, geen bemiddeling, geen beloftes.",
    "body": "## Afspraken vooraf in Nijmegen\n\n- **Scope en rol**: wat bewaak je precies, en wat valt er buiten?\n- **Beslislijnen**: wie beslist bij wijziging, stop of escalatie?\n- **Randvoorwaarden**: toegang, middelen, rapportage en overdracht.\n\n## Lokale context\n\nElke stad heeft eigen fricties: bereikbaarheid, type locaties en werkritme. Deze werkkaart helpt\nom die context expliciet te maken vóórdat er afspraken worden gemaakt.\n\n## Wat ProBrandwacht wel/niet doet\n\n- **Wel**: uitleg, context en afbakening van rollen en verwachtingen.\n- **Niet**: bemiddelen, prijssturing, garanties, of compliance-oplossingen verkopen.\n\n## Samenwerking in de praktijk\n\nAfspraken worden 1-op-1 gemaakt en blijven contextafhankelijk. ProBrandwacht beschrijft wat\nuitlegbaar samenwerken vraagt, maar lost het niet voor je op.\n\n## Vragen om vooraf te stellen\n\n- Welke signalen betekenen: pauzeren, stoppen, opschalen?\n- Welke documentatie moet later uitlegbaar zijn?\n- Wat is de rol van opdrachtgever vs. professional op locatie?",
    "localCaseTitle": "Voorbeeld: context in Nijmegen",
    "localCaseBody": "Een opdrachtgever en professional hebben vooraf rol, bereikbaarheid en escalatie afgesproken. ProBrandwacht beschrijft zulke kaders; uitvoering en afspraken blijven bij de betrokken partijen."
  }
};
